pre-commit:
  jobs:
    - group:
        parallel: true
        jobs:
          - run: bun run eslint {staged_files} --fix --cache --cache-location node_modules/.cache
            glob: '*.{js,ts,tsx}'
            stage_fixed: true
          - run: bun run stylelint {staged_files} --fix --cache --cache-location node_modules/.cache
            glob: '*.css'
            stage_fixed: true
    - run: bun run prettier {staged_files} --write --cache --ignore-unknown
      stage_fixed: true
