pre-commit:
  jobs:
    - group:
        parallel: true
        jobs:
          - run: bun run --if-present lint {staged_files}
            glob: '*.{js,ts,tsx}'
            stage_fixed: true
          - run: bun run --if-present styles {staged_files}
            glob: '*.css'
            stage_fixed: true
    - run: bun run --if-present format --check {staged_files}
      stage_fixed: true
